const test=require('node:test');const assert=require('node:assert/strict');
const b=require('../server/blanket.cjs');const {hash}=require('../server/domain.cjs');const {GitHubStore}=require('../server/store.cjs');
const milestone={id:'m1',title:'첫 시도',why:'작게 확인',steps:['실험'],minutes:60,checks:['읽히나요?','작동하나요?'],ifStuck:'범위를 줄여요',status:'todo',completion:null};
function fixture(){const users={a:{workspaceId:'w',name:'A',profile:{interests:'A only'}},b:{workspaceId:'w',name:'B',profile:{interests:'B only'}},c:{workspaceId:'other',name:'C'}};const make=(id,creator,visibility,workspaceId='w')=>({id,creatorId:creator,workspaceId,visibility,owner:creator,milestones:[structuredClone(milestone)],revision:1,assumptions:[]});return {users,projects:{ap:make('ap','a','private'),bp:make('bp','b','private'),shared:make('shared','a','shared'),foreign:make('foreign','c','shared','other')}};}
const actor=id=>({id,workspaceId:id==='c'?'other':'w'});
class Store{constructor(s){this.s=s;}async mutate(fn){const s=structuredClone(this.s);const r=fn(s);this.s=s;return r;}}
test('Two people share projects without sharing private projects or profiles',()=>{const s=fixture();assert.deepEqual(b.list(s,actor('a')).projects.map(p=>p.id),['ap','shared']);assert.deepEqual(b.list(s,actor('b')).projects.map(p=>p.id),['bp','shared']);assert.deepEqual(b.list(s,actor('b')).members,[{id:'a',name:'A'},{id:'b',name:'B'}]);assert.throws(()=>b.project(s,actor('b'),'ap'),/찾을 수/);assert.throws(()=>b.project(s,actor('c'),'shared'),/찾을 수/);});
test('Private projects cannot be assigned to another person',()=>{const s=fixture();const raw={md:'## 하려는 일\n함께 만들 작은 작업입니다.',visibility:'private',owner:'b',pace:'relaxed',weeklyMinutes:60,startDate:'2026-09-28',targetDate:''};assert.throws(()=>b.validateInput(raw,actor('a'),s),/나에게만/);assert.throws(()=>b.validateInput({...raw,visibility:'shared',owner:'c'},actor('a'),s),/같은 공간/);assert.throws(()=>b.validateInput({...raw,owner:'a',startDate:'2026-02-30'},actor('a'),s),/날짜/);});
test('MD parsing treats frontmatter as data, rejects malformed YAML',()=>{assert.equal(b.parseMD('---\ntitle: "그림 실험"\n---\n## 목표\n재료의 차이를 비교하는 작은 그림').title,'그림 실험');assert.throws(()=>b.parseMD('---\ntitle: [bad\n---\n내용이 충분한 실행 계획입니다.'),/머리말/);});
test('Relaxed pace leaves reserve and reports impossible target dates',()=>{const p={milestones:[milestone]};const input={pace:'focused',weeklyMinutes:60,startDate:'2026-09-28',targetDate:'2026-09-29'};const a=b.schedule(p,input,{factor:1});const relaxed=b.schedule(p,{...input,pace:'relaxed'},{factor:1});assert.equal(a.targetConflict,true);assert.ok(relaxed.milestones[0].due>a.milestones[0].due);});
test('Completion requires ownership, all checks, notes and matching revision',async()=>{const store=new Store(fixture());const data={projectId:'ap',milestoneId:'m1',revision:1,answers:[true,true],note:'두 조건을 직접 확인했습니다.',actualMinutes:75};await assert.rejects(()=>b.complete(store,actor('b'),data),/찾을 수/);await assert.rejects(()=>b.complete(store,actor('a'),{...data,answers:[true,false]}),/완료 기준/);await assert.rejects(()=>b.complete(store,actor('a'),{...data,note:'완료'}),/다섯 글자/);await assert.rejects(()=>b.complete(store,actor('a'),{...data,revision:3}),/다른 기기/);await b.complete(store,actor('a'),data);assert.equal(store.s.projects.ap.milestones[0].status,'done');assert.equal(store.s.projects.ap.milestones[0].completion.actualMinutes,75);await assert.rejects(()=>b.complete(store,actor('a'),data),/다른 기기/);});
test('Partial notes never award completion and future steps stay blocked',async()=>{const s=fixture();s.projects.ap.milestones.push({...structuredClone(milestone),id:'m2'});const store=new Store(s);await b.note(store,actor('a'),{projectId:'ap',milestoneId:'m1',note:'중간까지 했고 연결이 막힘'});assert.equal(store.s.projects.ap.milestones[0].status,'todo');await assert.rejects(()=>b.complete(store,actor('a'),{projectId:'ap',milestoneId:'m2',revision:2,answers:[true,true],note:'결과를 확인했습니다.'}),/앞 단계/);});
test('Velocity uses only my measured completions and needs three observations',()=>{const s=fixture();s.projects.bp.milestones[0].completion={actorId:'b',actualMinutes:6000};assert.equal(b.velocity(s,actor('a')).factor,1);s.projects.ap.milestones=[1,2,3].map(i=>({...milestone,id:`m${i}`,completion:{actorId:'a',actualMinutes:120}}));assert.equal(b.velocity(s,actor('a')).factor,2);assert.equal(b.velocity(s,actor('b')).factor,1);});
test('Personal pitch API always uses authenticated owner, ignores supplied user id',async()=>{const handler=require('../api/vault.js');const originals={assertPrivate:GitHubStore.prototype.assertPrivate,state:GitHubStore.prototype.state,pitch:GitHubStore.prototype.pitch};let requestedOwner;GitHubStore.prototype.assertPrivate=async()=>{};GitHubStore.prototype.state=async()=>({users:{a:{workspaceId:'w'},b:{workspaceId:'w'}},sessions:[{digest:hash('session-a'),uid:'a',expiresAt:Date.now()+10000}]});GitHubStore.prototype.pitch=async(uid,date)=>{requestedOwner=uid;return {issueDate:date,title:'A private pitch'};};const res={setHeader(){},status(n){this.code=n;return this;},json(v){this.value=v;return this;}};try{await handler({method:'GET',headers:{cookie:'vault_session=session-a'},query:{action:'pitch',uid:'b',date:'2026-09-28'}},res);assert.equal(res.code,200);assert.equal(requestedOwner,'a');}finally{Object.assign(GitHubStore.prototype,originals);}});
