const test=require('node:test');const assert=require('node:assert/strict');
const {resolve,snapshot,ask}=require('../server/blanket-context.cjs');
const user={id:'a',workspaceId:'w',profile:{timezone:'Asia/Seoul'}};
const m=(id,status='todo')=>({id,title:id,steps:['첫 동작 '+id],checks:['확인 '+id],ifStuck:'범위를 줄이기',status,due:'2026-10-01',minutes:30});
const p=(id,title,creator='a',visibility='private',workspaceId='w')=>({id,title,creatorId:creator,workspaceId,visibility,revision:1,milestones:[m('m1'),m('m2'),m('m3')]});
function fixture(){return {users:{a:{sampleProjects:{demo:{...p('demo','한글파파'),sample:true}}}},projects:{papa:p('papa','한글파파'),secret:p('secret','비밀 작업','b'),joint:p('joint','함께 그림','b','shared'),foreign:p('foreign','다른 공간','b','shared','other')}};}
test('Context resolves spaced Korean and English aliases only inside visible projects',()=>{const state=fixture();assert.equal(resolve(state,user,{message:'한글 파파 지금 뭘 하지?'}).project.id,'papa');assert.equal(resolve(state,user,{message:'hangul papa status'}).project.id,'papa');for(const title of ['비밀 작업','다른 공간']){const r=resolve(state,user,{message:title});assert.ok(!r.project);assert.deepEqual(r.choices.map(x=>x.id),['papa','joint']);}assert.ok(!resolve(state,user,{message:'뭐하지',projectId:'secret'}).project);});
test('Samples never substitute for real projects and ambiguity requires choice',()=>{const state=fixture();assert.equal(resolve(state,user,{demo:true,message:'한글파파'}).project.id,'demo');state.projects.other=p('other','한글파파');assert.equal(resolve(state,user,{message:'한글파파'}).choices.length,2);assert.equal(resolve(state,user,{message:'선택한 작업',projectId:'other'}).project.id,'other');});
test('Guidance skips finished work, preserves order and grounds latest note',()=>{const project=p('papa','한글파파');project.milestones[0]={...m('m1','done'),completion:{note:'첫 화면 테스트 완료',completedAt:'2026-09-28T10:00:00Z'}};project.milestones[1].notes=[{text:'다음 화면에서 멈춤',at:'2026-09-29T10:00:00Z'}];const r=snapshot(project);assert.deepEqual(r.steps.map(s=>s.id),['m2','m3']);assert.equal(r.steps[0].blockedBy,null);assert.equal(r.steps[1].blockedBy,'m2');assert.equal(r.lastRecord.text,'다음 화면에서 멈춤');assert.equal(r.completed.length,1);assert.equal(project.milestones[1].status,'todo');});
test('Completed projects have no invented next segment',()=>{const project=p('papa','한글파파');project.milestones.forEach(m=>m.status='done');assert.equal(snapshot(project).steps.length,0);});
test('Budget fallback still returns records without mutating project progress',async()=>{const state=fixture();const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());state.users.a.contextUsage={[day]:40};const before=structuredClone(state.projects);const store={state:async()=>state,mutate:async fn=>fn(state)};const r=await ask(store,user,{message:'한글파파 지금 상황은?'});assert.equal(r.source,'records');assert.ok(r.notice);assert.deepEqual(state.projects,before);});
