const test=require('node:test');const assert=require('node:assert/strict');
const {defaults,hash,localClock,validatePitch,markdown}=require('../server/domain.cjs');
const {authenticate,join,login}=require('../server/auth.cjs');
const {GitHubStore}=require('../server/store.cjs');
const council=require('../server/council.cjs');const jobs=require('../server/jobs.cjs');
const rag=require('../server/rag-client.cjs');
const cat='cat:WyJwc3ljaG9sb2d5Il0';
const ragMock=async(store,uid,input)=>({status:'connected',version:'live',checkedAt:new Date().toISOString(),categories:[{id:cat,name:'psychology',path:['psychology'],parentId:null,searchable:1,chunks:1}],results:input.excludedIds?.includes(cat)?[]:[{id:'unit1',title:'관찰',text:'공공장소의 행동과 시선',categoryIds:[cat],sources:[],revision:'live'}],searchVerified:true});
rag.request=ragMock;
const sample={title:'새로운 파동',hook:'작게 움직이는 글자를 만드는 실험',genre:'인터랙션 아트',whyYou:['움직임에 관심을 적었어요.'],experience:['쓴다','움직인다','느낀다'],mvp:['한 화면'],excluded:['결제'],approach:['Canvas 실험'],firstExperiment:{action:'한 줄 움직이기',minutes:45,success:'다시 만지고 싶은가',change:'읽기 어렵다면 줄이기'},opportunity:'재미있는 표현',objection:'반복할 이유가 있는가',decision:'한 화면으로 검증',unknowns:['반응 확인 필요'],sourceIds:['profile']};
class MemoryStore{
 constructor(s){this.s=structuredClone(s);this.docs={};this.writes=0;this.tail=Promise.resolve();}
 async state(){return structuredClone(this.s);}
 async mutate(fn){const run=this.tail.then(()=>{const next=structuredClone(this.s);const result=fn(next);this.s=next;return result;});this.tail=run.catch(()=>{});return run;}
 async savePitch(uid,p){const key=uid+'/'+p.issueDate;if(this.docs[key]&&this.docs[key].contentHash!==p.contentHash)throw new Error('PITCH_ALREADY_PUBLISHED');if(!this.docs[key]){this.docs[key]=structuredClone(p);this.writes++;}return this.docs[key];}
}
function initial(){return {workspaceId:'test-space',users:{u:{profile:{...defaults('나'),interests:'움직임과 예술'},archive:[],feedback:{},jobs:{},subscriptions:[]}},sessions:[],invites:[]};}
test('Seoul local issue dates stay correct at UTC midnight boundaries',()=>{assert.equal(localClock('Asia/Seoul',new Date('2026-09-28T14:59:00Z')).date,'2026-09-28');assert.equal(localClock('Asia/Seoul',new Date('2026-09-28T15:00:00Z')).date,'2026-09-29');assert.equal(localClock('Asia/Seoul',new Date('2026-09-28T00:00:00Z')).time,'09:00');});
test('Schema rejects unknown evidence and keeps MD a draft',()=>{assert.throws(()=>validatePitch(sample,[]),/UNKNOWN_SOURCE/);const p=validatePitch(sample,['profile']);const md=markdown({...p,id:'id',issueDate:'2026-09-28'});assert.match(md,/owner: unassigned/);assert.match(md,/target_date: null/);assert.match(md,/## 끝났다고 볼 기준/);assert.doesNotMatch(md,/project_id: id/);});
test('Sessions are expiring, opaque and owner-bound',()=>{const s=initial();s.users.other={name:'다른 사람'};s.sessions.push({digest:hash('test-secret'),uid:'u',expiresAt:Date.now()+10000});assert.equal(authenticate({headers:{cookie:'vault_session=test-secret'}},s).id,'u');assert.throws(()=>authenticate({headers:{cookie:'vault_session=other'}},s),/AUTH_REQUIRED/);s.sessions[0].expiresAt=0;assert.throws(()=>authenticate({headers:{cookie:'vault_session=test-secret'}},s),/AUTH_REQUIRED/);});
test('Invites are single-use and passwords are never stored plaintext',async()=>{const s=initial();s.users={};s.invites=[{digest:hash('invite'),role:'owner',expiresAt:Date.now()+10000}];const store=new MemoryStore(s);let cookie;const res={setHeader:(k,v)=>cookie=v};await join(store,{invite:'invite',username:'owner',name:'나',password:'long-enough-password'},res);const u=Object.values(store.s.users)[0];assert.notEqual(u.passwordHash,'long-enough-password');assert.ok(cookie.includes('HttpOnly; Secure; SameSite=Strict'));await assert.rejects(()=>join(store,{invite:'invite',username:'second',name:'아내',password:'another-long-password'},res),/INVITE_INVALID/);await assert.rejects(()=>login(store,{username:'owner',password:'wrong'}, {},res),/LOGIN_FAILED/);await login(store,{username:'owner',password:'long-enough-password'}, {},res);assert.equal(store.s.sessions.length,2);});
test('GitHub compare-and-swap retries on real revision conflicts',async()=>{const store=new GitHubStore();let calls=0;store.read=async()=>({sha:String(calls),value:{count:calls}});store.write=async()=>{calls++;if(calls===1)throw Object.assign(new Error('conflict'),{upstream:409});};const count=await store.mutate(s=>++s.count);assert.equal(count,2);assert.equal(calls,2);});
test('Private storage refuses a public repository',async()=>{const store=new GitHubStore();store.request=async()=>({private:false});await assert.rejects(()=>store.assertPrivate(),/STORAGE_MUST_BE_PRIVATE/);});
test('Push endpoint validation rejects internal and lookalike hosts',()=>{assert.equal(jobs.safePublicUrl('https://web.push.apple.com/test'),true);assert.equal(jobs.safePublicUrl('https://127.0.0.1/secret'),false);assert.equal(jobs.safePublicUrl('https://fcm.googleapis.com.evil.example/'),false);assert.equal(jobs.safePublicUrl('http://fcm.googleapis.com/x'),false);});
test('A/B independent input, cross review, one publish, saved partial failure',async()=>{const store=new MemoryStore(initial());const calls=[];let fail=true;const original=council.call;council.call=async(stage,ctx)=>{calls.push({stage,ctx:structuredClone(ctx)});if(stage==='B0'&&fail){fail=false;throw new Error('MODEL_503');}return {value:stage==='F'?sample:stage==='N'?{duplicate:false,preservesIntent:true,matchingId:'',reason:'새로운 경험',difference:'다른 핵심 행동'}:{summary:stage,ideas:[],risks:[],questions:[]},model:'test-model',usage:{}};};try{const [a,b]=await Promise.all([jobs.startRun(store,'u'),jobs.startRun(store,'u')]);assert.equal(a.date,b.date);await assert.rejects(()=>jobs.advance(store,'u',a.date),/MODEL_503/);assert.ok(store.s.users.u.jobs[a.date].nodes.A0);assert.equal(store.s.users.u.jobs[a.date].nodes.B0,undefined);store.s.users.u.jobs[a.date].nextRetryAt=0;await jobs.advance(store,'u',a.date);await jobs.advance(store,'u',a.date);await jobs.advance(store,'u',a.date);await jobs.advance(store,'u',a.date);assert.equal(store.writes,1);assert.equal(store.s.users.u.archive.length,1);assert.equal(calls.filter(x=>x.stage==='A0').length,1);assert.deepEqual(calls[0].ctx.brief,calls[1].ctx.brief);assert.equal(calls[0].ctx.B0,undefined);assert.equal(calls[1].ctx.A0,undefined);const a1=calls.find(x=>x.stage==='A1');assert.equal(a1.ctx.A0.summary,'A0');assert.equal(a1.ctx.B0.summary,'B0');assert.equal(a1.ctx.B1,undefined);assert.equal(store.s.users.u.jobs[a.date].notification.status,'pending');}finally{council.call=original;}});
test('Unknown model evidence never becomes a valid published document',()=>{assert.throws(()=>validatePitch({...sample,sourceIds:['invented-live-research']},['profile']),/UNKNOWN_SOURCE/);});

test('Conversation drafts require exact revision approval, lock after confirmation, and coexist with the daily run',async()=>{
 const conversations=require('../server/conversations.cjs');const store=new MemoryStore(initial());const original=council.call;council.call=async()=>({value:{reply:'장면을 기획서로 정리했습니다.',pitch:sample}});
 try{const d=await conversations.chat(store,'u',{message:'언리얼 엘리베이터',revision:0});assert.equal(d.revision,1);assert.equal(Object.keys(store.s.users.u.jobs).length,0);await assert.rejects(()=>jobs.startRun(store,'u',{draftId:d.id,revision:0}),/버전/);const r=await jobs.startRun(store,'u',{draftId:d.id,revision:1});const daily=await jobs.startRun(store,'u');assert.notEqual(r.date,daily.date);assert.equal(store.s.users.u.jobs[r.date].brief.approvedBrief.originalRequest,'언리얼 엘리베이터');assert.equal((await jobs.startRun(store,'u',{draftId:d.id,revision:1})).date,r.date);await assert.rejects(()=>conversations.chat(store,'u',{id:d.id,revision:1,message:'추가'}),/확정/);await assert.rejects(()=>conversations.chat(store,'u',{id:'other-person-id',message:'읽기'}),/찾을 수/);}finally{council.call=original;}
});
test('A completion is persisted while B is still running',async()=>{
 const store=new MemoryStore(initial());const original=council.call;let release;const hold=new Promise(r=>release=r);council.call=async stage=>{if(stage==='B0')await hold;return {value:{summary:stage,ideas:[],risks:[],questions:[]}};};
 try{const run=await jobs.startRun(store,'u');const running=jobs.advance(store,'u',run.date);await new Promise(r=>setImmediate(r));assert.ok(store.s.users.u.jobs[run.date].nodes.A0);assert.equal(store.s.users.u.jobs[run.date].nodes.B0,undefined);release();await running;}finally{release();council.call=original;}
});
test('Semantic duplicate is rewritten once and never published if still duplicate',async()=>{
 const store=new MemoryStore(initial());const original=council.call;council.call=async stage=>({value:stage==='F'?sample:stage==='N'?{duplicate:true,preservesIntent:true,reason:'문자를 물결로 바꾸는 동일한 경험',difference:'',matchingId:'prior'}:{summary:stage,ideas:[],risks:[],questions:[]}});
 try{const run=await jobs.startRun(store,'u');for(let i=0;i<5;i++)await jobs.advance(store,'u',run.date);await assert.rejects(()=>jobs.advance(store,'u',run.date),/DUPLICATE_PITCH/);assert.equal(store.writes,0);assert.equal(store.s.users.u.jobs[run.date].attempts.F,2);}finally{council.call=original;}
});
test('Live RAG preserves exclusions and fails closed when unavailable',async()=>{
 const knowledge=require('../server/knowledge.cjs'),store=new MemoryStore(initial());
 assert.equal((await knowledge.retrieve(store,store.s.users.u,'2026-09-29')).evidence[0].status,'firebase_active');
 store.s.users.u.exploration={categoryIds:[],excludedIds:[cat],formats:[]};
 await assert.rejects(()=>knowledge.retrieve(store,store.s.users.u,'2026-09-29'),/RAG_NO_MATCH/);
 rag.request=async()=>{throw new Error('RAG_UPSTREAM_503');};
 try{assert.equal((await knowledge.publicKnowledge(store.s.users.u,store)).status,'unavailable');await assert.rejects(()=>knowledge.retrieve(store,store.s.users.u,'2026-09-29'),/RAG_UPSTREAM/);}finally{rag.request=ragMock;}
});
