import React,{useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,Plus,Check,Loader2,ChevronRight,Link2} from 'lucide-react';
const CE='https://chunking-express-git-build-foundation-blanket2.vercel.app';
const labels={A0:'A · 가능성 찾기',B0:'B · 독립 검토',A1:'A · 방향 다듬기',B1:'B · 조건 점검',F:'한 장으로 정리',N:'반복·의도 확인'};
export function Progress({job,busy}){if(!job&&!busy)return null;return <section className="live-review" aria-label="검토 진행"><div className="studio-line"><strong>{job?.status==='published'?'검토 완료':job?.status==='failed'?'검토 보류':'함께 검토 중'}</strong><span>{job?.stages?.length||0}/6</span></div><div aria-live="polite">{(job?.progress||[]).map(p=><div className="review-event" key={p.stage}><Check size={15}/><div><b>{labels[p.stage]}</b><p>{p.summary}</p></div></div>)}{job?.activeStages?.map(s=><div className="review-event" key={s}><Loader2 size={15} className="spin"/><b>{labels[s]}</b></div>)}{!job?.stages?.length&&!job?.activeStages?.length&&busy&&<p>관심과 이전 제안을 불러오고 있어요.</p>}{job?.lastGate&&<p className="gate-note">다시 다듬는 중 · {job.lastGate.reason}</p>}{job?.error&&<p className="error-note">{job.error}</p>}</div></section>}
export function Conversation({api,onConfirm,renderPitch,onError,busy}){
 const[items,setItems]=useState([]),[current,setCurrent]=useState(null),[text,setText]=useState(''),[sending,setSending]=useState(false),[version,setVersion]=useState(null);
 const end=useRef(null);
 useEffect(()=>{api('conversations').then(r=>{setItems(r.conversations);setCurrent(r.conversations.find(d=>!d.runKey)||null);}).catch(e=>onError(e.message));},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[current?.messages.length,sending]);
 async function send(e){e.preventDefault();if(!text.trim()||sending)return;setSending(true);try{const r=await api('chat',{id:current?.id,revision:current?.revision||0,message:text});setCurrent(r.conversation);setVersion(null);setItems(xs=>[r.conversation,...xs.filter(x=>x.id!==r.conversation.id)]);setText('');}catch(e){onError(e.message);}finally{setSending(false);}}
 const shown=version?current?.versions.find(v=>v.revision===version)?.pitch:current?.pitch;
 return <section className="idea-conversation"><div className="studio-line"><div className="conversation-tabs"><MessageCircle size={18}/><select aria-label="저장된 대화" value={current?.id||''} onChange={e=>{setCurrent(items.find(d=>d.id===e.target.value)||null);setVersion(null);setText('');}} disabled={sending||busy}><option value="">새 대화</option>{items.map(d=><option key={d.id} value={d.id}>{d.pitch?.title||'기획 중'}{d.runKey?' · 확정':''}</option>)}</select></div><button disabled={sending||busy} className="text-button" onClick={()=>{setCurrent(null);setVersion(null);setText('');}}><Plus size={16}/>새 대화</button></div><div className="conversation-grid"><div className="chat-pane"><div className="chat-messages">{!current?.messages.length&&<div className="chat-welcome"><h2>어떤 걸 만들고 싶나요?</h2><p>장면, 목적, 가진 기술을 자유롭게 적어주세요.</p></div>}{current?.messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}>{m.text}</div>)}{sending&&<div className="chat-message assistant"><Loader2 className="spin" size={16}/> 기획서에 반영하고 있어요.</div>}<div ref={end}/></div><form onSubmit={send}><textarea aria-label="아이디어 대화" placeholder="예: 전 세계 사람들이 참여하는 엘리베이터. 언리얼로 만들고 싶고, 블렌더와 영상은 잘 다뤄요…" value={text} maxLength={6000} onChange={e=>setText(e.target.value)} disabled={sending||!!current?.runKey||busy}/><button className="primary" disabled={sending||busy||!text.trim()||!!current?.runKey}><Send size={16}/>{current?.pitch?'수정해서 보기':'기획서 만들기'}</button></form></div><div className="draft-pane">{shown?<><div className="studio-line"><select aria-label="기획서 버전" value={version||current.revision} onChange={e=>setVersion(Number(e.target.value))}>{current.versions.map(v=><option key={v.revision} value={v.revision}>기획서 v{v.revision}</option>)}</select><span>{current.runKey?'확정됨':'초안'}</span></div>{renderPitch({...shown,issueDate:current.createdAt.slice(0,10),id:'draft',evidence:[]},true)}<button className="primary confirm-brief" disabled={busy||sending||!!text.trim()||!!current.runKey||(version&&version!==current.revision)} onClick={()=>onConfirm(current,()=>setCurrent(d=>({...d,runKey:'confirmed'})))}><Check size={17}/>{current.runKey?'확정한 기획서':'이 기획으로 검토 시작'}</button>{text.trim()&&<small>입력한 내용을 먼저 기획서에 반영해 주세요.</small>}</>:<div className="draft-placeholder">대화하면 여기에 기획서가 만들어집니다.</div>}</div></div></section>
}
export function KnowledgeExplorer({api,onError,disabled}){
 const[data,setData]=useState(null),[domain,setDomain]=useState(''),[connecting,setConnecting]=useState(false);const popup=useRef(null),nonce=useRef('');
 useEffect(()=>{api('knowledge').then(setData).catch(e=>onError(e.message));},[]);
 useEffect(()=>{async function receive(e){if(e.origin!==CE||e.source!==popup.current||e.data?.type!=='markov-knowledge'||e.data.nonce!==nonce.current)return;nonce.current='';setConnecting(true);try{await api('knowledge-import',e.data.bundle);setData(await api('knowledge'));popup.current?.postMessage({type:'markov-knowledge-ack',ok:true},CE);}catch(err){onError(err.message);}finally{setConnecting(false);}}window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[]);
 if(!data)return null;
 async function choose(key,id){const previous=data.selection;const value={...previous,[key]:previous[key].includes(id)?previous[key].filter(v=>v!==id):[...previous[key],id]};if(key==='categoryIds')value.excludedIds=value.excludedIds.filter(v=>v!==id);if(key==='excludedIds')value.categoryIds=value.categoryIds.filter(v=>v!==id);setData(d=>({...d,selection:value}));try{await api('exploration',value);}catch(e){setData(d=>({...d,selection:previous}));onError(e.message);}}
 function connect(){nonce.current=crypto.randomUUID();popup.current=window.open(`${CE}/?blanket=${nonce.current}`,'blanket-knowledge','width=1050,height=800');if(!popup.current)onError('팝업을 허용한 뒤 다시 연결해 주세요.');}
 const active=data.taxonomy.domains.find(d=>d.id===domain);
 return <details className="knowledge-explorer"><summary>관심 지도 <span>{data.count?`지식 ${data.count}개`:'RAG 연결하기'}</span></summary><div className="studio-line"><span>{data.updatedAt?`지식 받은 날 ${data.updatedAt.slice(0,10)}`:'청킹익스프레스의 승인된 지식'}</span><button className="text-button" disabled={connecting||disabled} onClick={connect}><Link2 size={15}/>{connecting?'저장 중':'지식 가져오기'}</button></div><div className="category-chips">{data.taxonomy.domains.map(d=><button key={d.id} className={domain===d.id?'selected':''} onClick={()=>setDomain(domain===d.id?'':d.id)}>{d.number} {d.name}<ChevronRight size={13}/></button>)}</div>{active&&<div className="category-topics"><div className="studio-line"><strong>{active.name}</strong><div><button disabled={disabled} aria-pressed={data.selection.categoryIds.includes(active.id)} onClick={()=>choose('categoryIds',active.id)}>분야 탐색</button><button disabled={disabled} aria-pressed={data.selection.excludedIds.includes(active.id)} onClick={()=>choose('excludedIds',active.id)}>잠시 제외</button></div></div>{active.topics.map(t=><button disabled={disabled} key={t.id} className={data.selection.categoryIds.includes(t.id)?'selected':''} onClick={()=>choose('categoryIds',t.id)} title={t.question}>{t.number} {t.name}</button>)}</div>}<div className="category-chips">{[['software','앱·소프트웨어'],['interaction','인터랙션 아트'],['animation','영상·애니메이션'],['physical','실물 작업'],['life','생활·가족']].map(([id,label])=><button disabled={disabled} className={data.selection.formats.includes(id)?'selected':''} key={id} onClick={()=>choose('formats',id)}>{label}</button>)}</div><small>{data.selection.categoryIds.length?`${data.selection.categoryIds.length}개 분류 선택`:'전체 분야에서 탐색'}{data.selection.excludedIds.length?` · ${data.selection.excludedIds.length}개 제외`:''}</small></details>
}
