import React,{useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,Plus,Check,Loader2,ChevronRight,Link2} from 'lucide-react';
const labels={A0:'A · 가능성 찾기',B0:'B · 독립 검토',A1:'A · 방향 다듬기',B1:'B · 조건 점검',F:'한 장으로 정리',N:'반복·의도 확인'};
export function Progress({job,busy}){const[expanded,setExpanded]=useState(false);if(!job&&!busy)return null;return <section className="live-review" aria-label="검토 진행"><div className="studio-line"><strong>{job?.status==='published'?'검토 완료':job?.status==='failed'?'검토 보류':'함께 검토 중'}</strong><span>{job?.stages?.length||0}/6</span></div><div aria-live="polite">{(job?.progress?.length||0)>3&&<button className="text-button" onClick={()=>setExpanded(v=>!v)}>{expanded?'핵심만 보기':'앞선 검토 보기'}</button>}{(expanded?job?.progress||[]:(job?.progress||[]).slice(-3)).map(p=><div className="review-event" key={p.stage}><Check size={15}/><div><b>{labels[p.stage]}</b><p>{p.summary}</p></div></div>)}{job?.activeStages?.map(s=><div className="review-event" key={s}><Loader2 size={15} className="spin"/><b>{labels[s]}</b></div>)}{!job?.stages?.length&&!job?.activeStages?.length&&busy&&<p>관심과 이전 제안을 불러오고 있어요.</p>}{job?.lastGate&&<p className="gate-note">다시 다듬는 중 · {job.lastGate.reason}</p>}{job?.error&&<p className="error-note">{job.error}</p>}</div></section>}
export function Conversation({api,onConfirm,renderPitch,onError,busy}){
 const[items,setItems]=useState([]),[current,setCurrent]=useState(null),[text,setText]=useState(''),[sending,setSending]=useState(false),[version,setVersion]=useState(null);
 const end=useRef(null);
 useEffect(()=>{api('conversations').then(r=>{setItems(r.conversations);setCurrent(r.conversations.find(d=>!d.runKey)||null);}).catch(e=>onError(e.message));},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[current?.messages.length,sending]);
 async function send(e){e.preventDefault();if(!text.trim()||sending)return;setSending(true);try{const r=await api('chat',{id:current?.id,revision:current?.revision||0,message:text});setCurrent(r.conversation);setVersion(null);setItems(xs=>[r.conversation,...xs.filter(x=>x.id!==r.conversation.id)]);setText('');}catch(e){onError(e.message);}finally{setSending(false);}}
 const shown=version?current?.versions.find(v=>v.revision===version)?.pitch:current?.pitch;
 return <section className="idea-conversation"><div className="studio-line"><div className="conversation-tabs"><MessageCircle size={18}/><select aria-label="저장된 대화" value={current?.id||''} onChange={e=>{setCurrent(items.find(d=>d.id===e.target.value)||null);setVersion(null);setText('');}} disabled={sending||busy}><option value="">새 대화</option>{items.map(d=><option key={d.id} value={d.id}>{d.pitch?.title||'기획 중'}{d.runKey?' · 확정':''}</option>)}</select></div><button disabled={sending||busy} className="text-button" onClick={()=>{setCurrent(null);setVersion(null);setText('');}}><Plus size={16}/>새 대화</button></div><div className="conversation-grid"><div className="chat-pane"><div className="chat-messages">{!current?.messages.length&&<div className="chat-welcome"><h2>어떤 걸 만들고 싶나요?</h2><p>장면, 목적, 가진 기술을 자유롭게 적어주세요.</p></div>}{current?.messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}>{m.text}</div>)}{sending&&<div className="chat-message assistant"><Loader2 className="spin" size={16}/> 기획서에 반영하고 있어요.</div>}<div ref={end}/></div><form onSubmit={send}><textarea aria-label="아이디어 대화" placeholder="예: 전 세계 사람들이 참여하는 엘리베이터. 언리얼로 만들고 싶고, 블렌더와 영상은 잘 다뤄요…" value={text} maxLength={6000} onChange={e=>setText(e.target.value)} disabled={sending||!!current?.runKey||busy}/><button className="primary" disabled={sending||busy||!text.trim()||!!current?.runKey}><Send size={16}/>{current?.pitch?'수정해서 보기':'기획서 만들기'}</button></form></div><div className="draft-pane">{shown?<><div className="studio-line"><select aria-label="기획서 버전" value={version||current.revision} onChange={e=>setVersion(Number(e.target.value))}>{current.versions.map(v=><option key={v.revision} value={v.revision}>기획서 v{v.revision}</option>)}</select><span>{current.runKey?'확정됨':'초안'}</span></div>{renderPitch({...shown,issueDate:current.createdAt.slice(0,10),id:'draft',evidence:[]},true)}<button className="primary confirm-brief" disabled={busy||sending||!!text.trim()||!!current.runKey||(version&&version!==current.revision)} onClick={()=>onConfirm(current,()=>setCurrent(d=>({...d,runKey:'confirmed'})))}><Check size={17}/>{current.runKey?'확정한 기획서':'이 기획으로 검토 시작'}</button>{text.trim()&&<small>입력한 내용을 먼저 기획서에 반영해 주세요.</small>}</>:<div className="draft-placeholder">대화하면 여기에 기획서가 만들어집니다.</div>}</div></div></section>
}
export function KnowledgeExplorer({api,onError,disabled}){
 const[data,setData]=useState(null),[domain,setDomain]=useState(''),[loading,setLoading]=useState(false),[probe,setProbe]=useState(null),[testing,setTesting]=useState(false);
 async function refresh(){setLoading(true);try{setData(await api('knowledge'));}catch{setData({status:'unavailable',categories:[],selection:{categoryIds:[],excludedIds:[],formats:[]}});}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 async function choose(key,id){const previous=data.selection;const value={...previous,[key]:previous[key].includes(id)?previous[key].filter(v=>v!==id):[...previous[key],id]};if(key==='categoryIds')value.excludedIds=value.excludedIds.filter(v=>v!==id);if(key==='excludedIds')value.categoryIds=value.categoryIds.filter(v=>v!==id);setData(d=>({...d,selection:value}));try{await api('exploration',value);}catch(e){setData(d=>({...d,selection:previous}));onError(e.message);}}
 async function testSearch(){setTesting(true);setProbe(null);try{setProbe(await api('knowledge-check',{}));}catch(e){setProbe({error:e.message});}finally{setTesting(false);}}
 const connected=data?.status==='connected',categories=data?.categories||[],roots=categories.filter(c=>!c.parentId),active=categories.find(c=>c.id===domain),max=Math.max(1,...roots.map(c=>c.chunks));
 const density=c=>({'--coverage':String(.08+.55*Math.log1p(c.chunks)/Math.log1p(max))});
 const selected=id=>data.selection.categoryIds.includes(id);
 return <details className="knowledge-explorer" open><summary>관심 지도 <span role="status">{loading?'Firebase 확인 중…':connected?'사주그랩 RAG 연결 성공':'사주그랩 RAG 연결 확인 필요'}</span></summary><div className="studio-line"><span>{loading?'운영 자료를 불러오고 있어요.':connected?`${data.chunks}개 청크 · 검색 가능 ${data.searchable}개`:'자료량을 확인하지 못했습니다.'}</span><button className="text-button" disabled={loading||disabled} onClick={refresh}>{loading?<Loader2 className="spin" size={15}/>:<Link2 size={15}/>}다시 확인</button></div>{connected&&<><div className="category-chips coverage-chips">{roots.map(c=><button key={c.id} style={density(c)} aria-expanded={domain===c.id} onClick={()=>setDomain(domain===c.id?'':c.id)}>{selected(c.id)&&<Check size={13}/>} {c.name}<b>{c.chunks}</b><ChevronRight size={13}/></button>)}</div>{!categories.length&&<p>운영 중인 RAG 자료가 없습니다.</p>}{active&&<div className="category-topics"><div className="studio-line"><strong>{active.name} · {active.chunks}개 청크</strong><div><button disabled={disabled||!active.searchable} aria-pressed={selected(active.id)} onClick={()=>choose('categoryIds',active.id)}>✓ 분야 선택</button><button disabled={disabled} aria-pressed={data.selection.excludedIds.includes(active.id)} onClick={()=>choose('excludedIds',active.id)}>잠시 제외</button></div></div>{categories.filter(c=>c.parentId===active.id).map(c=><button key={c.id} disabled={disabled||!c.searchable} aria-pressed={selected(c.id)} onClick={()=>choose('categoryIds',c.id)}>{selected(c.id)&&<Check size={13}/>} {c.name} · {c.chunks}</button>)}</div>}<div className="studio-line"><button className="text-button" disabled={testing||disabled||!data.searchable} onClick={testSearch}>{testing?'검색 확인 중…':'검색 테스트'}</button>{probe&&<span role="status">{probe.error|| (probe.verified?'실제 검색 성공':'검색 결과 없음')}</span>}</div>{probe?.verified&&<small>{probe.titles.join(' · ')}</small>}<small>진할수록 자료가 많아요 · {new Date(data.checkedAt).toLocaleString('ko-KR')} 확인</small><details className="knowledge-counts"><summary>집계 기준</summary><small>운영 자료만 표시 · 지식 ID {data.knowledgeCount}개 · 지식 ID 없는 청크 {data.unidentifiedChunks}개<br/>분류는 Firebase의 원본 값입니다. 청크 수는 독립된 지식 수와 다릅니다.</small></details></>}{data&&<><div className="category-chips">{[['software','앱·소프트웨어'],['interaction','인터랙션 아트'],['animation','영상·애니메이션'],['physical','실물 작업'],['life','생활·가족']].map(([id,label])=><button disabled={disabled} className={data.selection.formats.includes(id)?'selected':''} key={id} onClick={()=>choose('formats',id)}>{label}</button>)}</div><small>{data.selection.categoryIds.filter(id=>categories.some(c=>c.id===id)).length||'전체'} 분야 탐색</small></>}</details>
}
