import React,{useState} from 'react';
import ProjectTimeline from './ProjectTimeline';
import './context-timeline.css';
import {ChevronLeft,ChevronRight,Check,ArrowUpRight} from 'lucide-react';
const add=(d,n)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
const short=d=>`${Number(d.slice(5,7))}월 ${Number(d.slice(8))}일`;
export default function ScheduleBoard({projects,today,onSelect,ownerName,tone,onMove,busy}){
 const base=today||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
 const[date,setDate]=useState(base),[view,setView]=useState('timeline'),[scale,setScale]=useState('week');
 const dow=new Date(date+'T00:00:00Z').getUTCDay(),monday=add(date,-((dow+6)%7));
 const days=Array.from({length:7},(_,i)=>add(monday,i));
 const first=date.slice(0,7)+'-01',monthStart=add(first,-((new Date(first+'T00:00:00Z').getUTCDay()+6)%7));
 const monthDays=Array.from({length:42},(_,i)=>add(monthStart,i));
 const timelineDays=scale==='day'?[date]:scale==='week'?days:Array.from({length:new Date(Number(date.slice(0,4)),Number(date.slice(5,7)),0).getDate()},(_,i)=>add(first,i));
 const items=projects.flatMap(p=>p.milestones.map(m=>({p,m}))).sort((a,b)=>a.m.due.localeCompare(b.m.due));
 const stage=({p,m})=>m.status==='done'?'done':m.stage||p.stage||'waiting';
 const select=(p,e)=>onSelect(p.id,e.currentTarget.getBoundingClientRect());
 function navigate(n){if(view==='month'||view==='timeline'&&scale==='month'){const d=new Date(first+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);setDate(d.toISOString().slice(0,10));}else setDate(add(date,n*(view==='week'||view==='timeline'&&scale==='week'?7:1)));}
 const tile=({p,m},compact=false)=><article key={p.id+m.id} className={`board-task ${tone(p.owner)} ${m.status==='done'?'is-done':''}`}><button className={`schedule-card ${tone(p.owner)} ${m.status==='done'?'is-done':''}`} onClick={e=>select(p,e)} aria-label={`${p.title} · ${m.title} · ${ownerName(p.owner)} · ${m.due}`}><span className="schedule-card-top"><span>{p.category||'프로젝트'}</span>{m.status==='done'?<Check size={15}/>:<ArrowUpRight size={14}/>}</span><small>{p.title}</small><strong>{m.title}</strong><span className="schedule-card-bottom"><span className="person-dot"/>{ownerName(p.owner)}<span>{m.minutes}분</span></span></button>{view==='status'&&!compact&&m.status!=='done'&&onMove&&<button className="stage-action" disabled={busy} onClick={()=>onMove(p,m,stage({p,m})==='active'?'waiting':'active')}>{stage({p,m})==='active'?'대기로':'시작하기'} <ArrowUpRight size={12}/></button>}</article>;
 const agenda=<section className={`day-agenda ${view==='week'?'week-agenda':''}`}><h3>{short(date)} <span>{items.filter(({m})=>m.due===date).length}개</span></h3><div>{items.filter(({m})=>m.due===date).map(item=>tile(item,true))}</div>{!items.some(({m})=>m.due===date)&&<p className="day-empty">등록된 일정이 없어요.</p>}</section>;
 return <section className={`scheduler scheduler-${view}`}><div className="scheduler-heading"><div className="week-navigation">{view!=='status'&&<button aria-label="이전 기간" onClick={()=>navigate(-1)}><ChevronLeft size={19}/></button>}<h2>{view==='status'?'전체 작업':view==='timeline'?scale==='day'?short(date):scale==='week'?`${short(days[0])} — ${short(days[6])}`:`${date.slice(0,4)}년 ${Number(date.slice(5,7))}월`:view==='week'?`${short(days[0])} — ${short(days[6])}`:view==='month'?`${date.slice(0,4)}년 ${Number(date.slice(5,7))}월`:short(date)}</h2>{view!=='status'&&<><button aria-label="다음 기간" onClick={()=>navigate(1)}><ChevronRight size={19}/></button><button className="today-button" onClick={()=>setDate(base)}>오늘</button></>}</div><div className="view-switch" aria-label="일정 보기">{[['timeline','타임라인'],['day','일'],['week','주'],['month','월'],['status','칸반']].map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)} aria-pressed={view===id}>{label}</button>)}</div></div>
 {view==='timeline'&&<><div className="timeline-toolbar"><span>흐름을 보고, 다시 이어가요.</span><div className="view-switch" aria-label="타임라인 범위">{[['day','일'],['week','주'],['month','월']].map(([id,label])=><button key={id} aria-pressed={scale===id} className={scale===id?'active':''} onClick={()=>setScale(id)}>{label}</button>)}</div></div><ProjectTimeline projects={projects} days={timelineDays} today={base} ownerName={ownerName} tone={tone} onSelect={onSelect}/></>}
 {view==='status'&&<div className="status-board">{[['waiting','대기'],['active','진행 중'],['done','완료']].map(([id,label])=><section key={id}><h3><i className={`stage-dot ${id}`}/>{label}<span>{items.filter(item=>stage(item)===id).length}</span></h3>{items.filter(item=>stage(item)===id).map(item=>tile(item))}{!items.some(item=>stage(item)===id)&&<p className="day-empty">—</p>}</section>)}</div>}
 {view==='week'&&<><div className="week-board">{days.map((day,i)=><section className={`day-column ${day===base?'is-today':''} ${day===date?'is-selected':''}`} key={day}><button className="day-heading" onClick={()=>setDate(day)} aria-label={`${short(day)} 일정 보기`} aria-pressed={day===date}><span>{['월','화','수','목','금','토','일'][i]}</span><strong>{Number(day.slice(8))}</strong></button><div className="day-cards">{items.filter(({m})=>m.due===day).map(item=>tile(item,true))}{!items.some(({m})=>m.due===day)&&<span className="day-empty">—</span>}</div></section>)}</div>{agenda}</>}
 {view==='month'&&<><div className="month-board"><div className="month-labels">{['월','화','수','목','금','토','일'].map(d=><span key={d}>{d}</span>)}</div><div className="month-grid">{monthDays.map(day=>{const entries=items.filter(({m})=>m.due===day);return <button key={day} className={`month-cell ${day.slice(0,7)!==date.slice(0,7)?'muted':''} ${day===base?'is-today':''} ${day===date?'selected':''}`} onClick={()=>setDate(day)} aria-label={`${day} · ${entries.length}개 일정`}><strong>{Number(day.slice(8))}</strong><div className="month-events">{entries.slice(0,2).map(({p,m})=><span key={p.id+m.id} className={tone(p.owner)}>{p.title}</span>)}{entries.length>2&&<small>+{entries.length-2}</small>}</div></button>;})}</div></div>{agenda}</>}
 {view==='day'&&agenda}
 </section>;
}
